pipeline {
  agent {
    docker { image 'python:3.13.7-alpine3.22' }
  }

  options {
    skipStagesAfterUnstable()
  }

  stages {
    stage('Setup') {
      steps {
        sh '''
          set -eu
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          mkdir -p test-reports
        '''
      }
    }

    stage('Build') {
      steps {
        sh '''
          set -eu
          . venv/bin/activate
          python -m py_compile sources/add2vals.py sources/calc.py
        '''
        stash name: 'compiled-results', includes: 'sources/*.py*'
      }
    }

    stage('Test') {
      steps {
        sh '''
          set -eu
          . venv/bin/activate
          py.test --junit-xml test-reports/results.xml sources/test_calc.py
        '''
      }
      post {
        always {
          junit 'test-reports/results.xml'
        }
        unstable {
          echo 'Тесты пометили билд как UNSTABLE'
        }
      }
    }

    stage('Deliver') {
      steps {
        echo 'Собираю дистрибутив'
      }
      post {
        success {
          archiveArtifacts artifacts: '**/*.py'
        }
      }
    }
  }
}
