pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.12.0-alpine3.18'
                }
            }
            steps {
                dir('sources') {
                    sh 'python -m py_compile add2vals.py calc.py'
                    stash(name: 'compiled-results', includes: '*.py*')
                }
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                dir('sources') {
                    sh 'py.test --junit-xml ../test-reports/results.xml test_calc.py'
                }
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }

        stage('Deliver') {
            agent {
                docker {
                    image 'python:2.7'
                }
            }
            steps {
                dir('sources') {
                    unstash(name: 'compiled-results')
                    sh '''
                        pip install pyinstaller
                        pyinstaller -F add2vals.py
                    '''
                }
            }
            post {
                success {
                    archiveArtifacts 'sources/dist/add2vals'
                }
            }
        }
    }
}
